import type { World } from "@/content/types";

export const chaptersA: World[] = [
  {
    id: "w1",
    name: "Capítulo 1: Quebrada",
    subtitle: "Primeiros comandos: print, variáveis e contas",
    emoji: "🏘️",
    color: "from-orange-500 to-rose-700",
    sky: ["#f97316", "#7c2d12"],
    skyline: "#3b1d14",
    levels: [
      {
        id: "1-1",
        title: "O teste da Dani",
        brief: [
          { who: "dani", text: "Primeiro teste, Léo. Atravesse a rua até a minha garagem. Cuidado com o drone da Vértice: um choque derruba ele." },
          { who: "dani", text: "O portão da garagem tem um terminal. Para abrir, ele precisa mostrar na tela a frase: Estou dentro" },
          { who: "dani", text: "Para mostrar algo na tela, o comando é `print`. Escreva `print`, abra parênteses e coloque a frase entre aspas: `print(\"oi\")`." },
          { who: "dani", text: "As aspas dizem ao computador que aquilo é texto, para copiar igualzinho. Uma letra diferente e o portão não abre." },
        ],
        task: "No terminal, mostre na tela exatamente: Estou dentro",
        theory: "`print()` mostra algo na tela. Texto vai entre aspas.",
        example: 'print("Bom dia")',
        starter: "",
        hints: ["Use print(...) com o texto entre aspas", 'print("Estou dentro")'],
        check: 'assert __out.strip() == "Estou dentro", f"A tela mostrou {__out.strip()!r}, mas precisava mostrar \'Estou dentro\'"',
        solution: 'print("Estou dentro")\n',
        explain: "`print` escreve na tela o que está entre os parênteses. As aspas marcam que `Estou dentro` é texto. O terminal compara letra por letra, então qualquer diferença mantém o portão fechado.",
        chips: ["print()", '""', "Estou dentro"],
        display: { kind: "screen" },
        target: "Portão da garagem",
        success: { who: "dani", text: "Portão aberto! Primeiro comando da sua vida e já invadiu um sistema. Corre para a garagem." },
        xp: 10,
      },
      {
        id: "1-2",
        title: "Identidade falsa",
        brief: [
          { who: "dani", text: "Você vai precisar de um crachá falso. O sistema de cadastro fica no fim do beco, e tem segurança do Caveira rondando." },
          { who: "dani", text: "O cadastro guarda informações em variáveis. Pense numa caixa com etiqueta: a etiqueta é o nome, e dentro fica o valor." },
          { who: "dani", text: "`codinome = \"Motoboy\"` quer dizer: guarde \"Motoboy\" na caixa chamada codinome. Aqui o `=` significa guardar, não é o igual da matemática." },
          { who: "dani", text: "Texto vai com aspas. Número vai sem aspas: `idade = 22`. Se colocar aspas no número, ele vira texto e o sistema recusa." },
        ],
        task: 'Crie a variável `codinome` com o texto "Motoboy" e a variável `idade` com o número 22.',
        theory: "Uma variável guarda um valor com um nome: `nome = valor`.",
        example: 'cidade = "Porto Seco"\nano = 2026',
        starter: "",
        hints: ["Texto com aspas, número sem aspas", 'codinome = "Motoboy"'],
        check: 'assert codinome == "Motoboy", "codinome precisa ser \\"Motoboy\\""\nassert idade == 22 and isinstance(idade, int), "idade precisa ser o número 22, sem aspas"',
        solution: 'codinome = "Motoboy"\nidade = 22\n',
        explain: "Cada variável nasce com `nome = valor`. \"Motoboy\" é texto e vai com aspas. 22 é número e vai sem aspas. Se fosse `\"22\"`, o sistema receberia texto e recusaria o cadastro.",
        chips: ["codinome", "idade", "=", '"Motoboy"', "22"],
        display: {
          kind: "locks",
          events: [
            { label: "Campo codinome", expr: "codinome", expect: "'Motoboy'" },
            { label: "Campo idade", expr: "idade", expect: "22" },
          ],
        },
        target: "Cadastro da Vértice",
        success: { who: "dani", text: "Crachá impresso. Para a Vértice, agora você é o Motoboy, 22 anos. Ninguém vai desconfiar." },
        xp: 10,
      },
      {
        id: "1-3",
        title: "A partilha",
        brief: [
          { who: "rui", text: "Conseguimos R$ 250 vendendo peças velhas. Somos 7 na equipe. Quanto fica para cada um e quanto sobra para a gasolina?" },
          { who: "dani", text: "O Python é uma calculadora. `+` soma, `-` subtrai, `*` multiplica e `/` divide." },
          { who: "dani", text: "Mas partilha não pode ter centavo quebrado. Para isso existe `//`, a divisão inteira: `7 // 2` dá 3. E `%` dá só o resto: `7 % 2` dá 1." },
          { who: "dani", text: "A variável `dinheiro` já está no terminal. Crie `cada` com a divisão inteira por 7 e `sobra` com o resto." },
        ],
        task: "Com `dinheiro = 250`, crie `cada` (quanto cada um dos 7 recebe, sem centavos) e `sobra` (o resto).",
        theory: "`//` é a divisão inteira e `%` é o resto da divisão.",
        example: "print(17 // 5, 17 % 5)  # 3 2",
        starter: "dinheiro = 250\n",
        hints: ["Use // e %", "cada = dinheiro // 7"],
        check: 'assert cada == 35, "cada deveria ser 35"\nassert sobra == 5, "sobra deveria ser 5"',
        solution: "dinheiro = 250\ncada = dinheiro // 7\nsobra = dinheiro % 7\n",
        explain: "7 × 35 = 245, e sobram 5. `//` descarta a parte quebrada e devolve 35. `%` devolve só o resto, 5. A divisão comum `/` daria 35.71, que não serve para dividir notas.",
        chips: ["cada", "sobra", "=", "dinheiro", "//", "%", "7"],
        display: {
          kind: "locks",
          events: [
            { label: "Parte de cada um", expr: "cada", expect: "35" },
            { label: "Sobra da gasolina", expr: "sobra", expect: "5" },
          ],
        },
        target: "Cofre da garagem",
        success: { who: "rui", text: "35 para cada um e 5 para a gasolina. Conta certa, equipe feliz." },
        xp: 15,
      },
      {
        id: "1-4",
        title: "O interfone",
        brief: [
          { who: "bia", text: "Oi, Léo, sou a Bia. A Vértice trocou o interfone do prédio onde guardo as ferramentas. Ele só abre se cumprimentar quem chega pelo nome." },
          { who: "dani", text: "O comando `input()` espera alguém digitar algo e entrega o que foi digitado. Guarde numa variável: `nome = input()`." },
          { who: "dani", text: "Para colocar a variável dentro de uma frase, use uma f-string: um `f` antes das aspas e o nome da variável entre chaves: `f\"Oi, {nome}\"`." },
          { who: "dani", text: "Quem vai chegar agora sou eu. O interfone vai digitar Dani, e precisa mostrar: Bem-vinda, Dani!" },
        ],
        task: "Leia um nome com `input()` e mostre: Bem-vinda, <nome>! (o interfone vai digitar Dani)",
        theory: "`input()` lê o que foi digitado, sempre como texto. f-strings colocam variáveis no texto: `f\"Oi {nome}\"`.",
        example: 'cidade = input()\nprint(f"Você está em {cidade}")',
        starter: "",
        inputs: ["Dani"],
        hints: ["nome = input()", 'print(f"Bem-vinda, {nome}!")'],
        check: 'assert "Bem-vinda, Dani!" in __out, "A tela precisava mostrar \'Bem-vinda, Dani!\'"',
        solution: 'nome = input()\nprint(f"Bem-vinda, {nome}!")\n',
        explain: "`input()` pegou o que foi digitado, Dani, e guardou em `nome`. A f-string colocou esse valor no meio da frase, e o `print` mostrou `Bem-vinda, Dani!`.",
        chips: ["nome", "=", "input()", "print()", 'f"Bem-vinda, {nome}!"'],
        display: { kind: "screen" },
        target: "Porta do prédio",
        success: { who: "bia", text: "A porta abriu! Peguei minhas ferramentas. Vou deixar o carro de fuga no ponto." },
        xp: 15,
      },
      {
        id: "1-5",
        title: "O cobrador do Caveira",
        boss: "baiano",
        brief: [
          { who: "baiano", text: "Motoboy! O Caveira mandou cobrar. Ou paga hoje, ou a sua moto fica comigo." },
          { who: "dani", text: "O Baiano guarda o dinheiro num cofre. A senha é a soma de dois números que o cofre informa, mas tem uma armadilha." },
          { who: "dani", text: "`input()` sempre entrega texto. E texto mais texto só gruda: `\"12\" + \"30\"` vira `\"1230\"`. Para somar de verdade, converta com `int()`: `int(\"12\")` vira o número 12." },
          { who: "dani", text: "Derrube o Baiano com a pistola de choque, chegue ao cofre, converta os dois números e mostre: Senha: 42. O cofre vai digitar 12 e 30." },
        ],
        task: "Leia dois números com `input()` (o cofre digita 12 e 30), some e mostre: Senha: 42",
        theory: "`int()` transforma texto em número inteiro. `input()` sempre devolve texto.",
        example: 'x = int("40") + 2  # 42',
        starter: "",
        inputs: ["12", "30"],
        hints: ["a = int(input())", 'print(f"Senha: {a + b}")'],
        check: 'assert "Senha: 42" in __out, "A tela precisava mostrar \'Senha: 42\'"',
        solution: 'a = int(input())\nb = int(input())\nprint(f"Senha: {a + b}")\n',
        explain: "Sem `int`, a conta juntaria os textos e daria 1230. Convertendo cada leitura para número, 12 + 30 dá 42, e a f-string monta a frase.",
        chips: ["int()", "input()", "a", "b", "=", "+", 'print(f"Senha: {a + b}")'],
        display: { kind: "screen" },
        target: "Cofre do Baiano",
        success: { who: "caveira", text: "Então o motoboy aprendeu a hackear... Aproveita, garoto. Da próxima vez sou eu que vou atrás de você." },
        xp: 40,
      },
    ],
  },
  {
    id: "w2",
    name: "Capítulo 2: Centro",
    subtitle: "Decisões com if, elif, else, and e or",
    emoji: "🏙️",
    color: "from-sky-500 to-indigo-800",
    sky: ["#38bdf8", "#1e1b4b"],
    skyline: "#111133",
    levels: [
      {
        id: "2-1",
        title: "A catraca do metrô",
        brief: [
          { who: "dani", text: "Precisamos atravessar o centro sem aparecer nas câmeras da rua. O caminho é pelo metrô, mas a Vértice controla as catracas." },
          { who: "dani", text: "Agora você vai ensinar o computador a decidir. O comando é `if`, que quer dizer \"se\". `if saldo >= 50:` significa: se o saldo for 50 ou mais, faça o que está logo abaixo." },
          { who: "dani", text: "Repare nos dois-pontos no fim da linha e nos 4 espaços na linha de baixo. Eles mostram o que pertence ao `if`." },
          { who: "dani", text: "`else:` quer dizer \"senão\": o que fazer quando a condição não acontece. O nosso cartão clonado tem 80 de saldo." },
        ],
        task: 'Com `saldo = 80`, mostre "Liberado" se o saldo for 50 ou mais, senão mostre "Bloqueado".',
        theory: "`if condição:` executa o bloco com recuo só se a condição for verdadeira. `else:` cobre o outro caso.",
        example: 'if chovendo:\n    print("Leva guarda-chuva")\nelse:\n    print("Pode ir")',
        starter: "saldo = 80\n",
        hints: ["if saldo >= 50:", "Dois-pontos no fim e 4 espaços na linha de baixo"],
        check: 'assert __out.strip() == "Liberado", "A catraca precisava mostrar Liberado"',
        solution: 'saldo = 80\nif saldo >= 50:\n    print("Liberado")\nelse:\n    print("Bloqueado")\n',
        explain: "80 é maior ou igual a 50, então o `if` entra no bloco e mostra `Liberado`. O `else` só rodaria se o saldo fosse menor.",
        chips: ["if", "else:", "saldo >= 50:", "print()", '"Liberado"', '"Bloqueado"'],
        display: { kind: "screen" },
        target: "Catraca do metrô",
        success: { who: "dani", text: "Catraca liberada. Você acabou de escrever sua primeira decisão." },
        xp: 15,
      },
      {
        id: "2-2",
        title: "Níveis de acesso",
        brief: [
          { who: "dani", text: "Os crachás da Vértice têm uma pontuação. O leitor decide o cargo pelos pontos, e vamos reprogramar esse leitor." },
          { who: "dani", text: "Quando há mais de dois caminhos, use `elif`, que é um \"senão, se\". O Python testa de cima para baixo e para no primeiro que der certo." },
          { who: "dani", text: "Você vai escrever uma função, uma receita com nome. `def nivel(pontos):` cria a receita nivel, que recebe os pontos. `return` entrega a resposta." },
          { who: "dani", text: "Menos de 100 pontos é Visitante, menos de 500 é Funcionário, e o resto é Diretor." },
        ],
        task: 'Crie `nivel(pontos)` que retorna "Visitante" (menos de 100), "Funcionário" (menos de 500) ou "Diretor".',
        theory: "`elif` testa outra condição quando a anterior falhou. `return` devolve o resultado da função.",
        example: 'def clima(graus):\n    if graus < 15:\n        return "frio"\n    elif graus < 28:\n        return "bom"\n    else:\n        return "quente"',
        starter: "def nivel(pontos):\n    pass\n",
        hints: ['if pontos < 100: return "Visitante"', "Depois elif pontos < 500 e, por fim, else"],
        check: 'assert nivel(10) == "Visitante", "10 pontos"\nassert nivel(100) == "Funcionário", "100 pontos deveria ser Funcionário"\nassert nivel(499) == "Funcionário", "499 pontos"\nassert nivel(500) == "Diretor", "500 pontos"',
        solution: 'def nivel(pontos):\n    if pontos < 100:\n        return "Visitante"\n    elif pontos < 500:\n        return "Funcionário"\n    else:\n        return "Diretor"\n',
        explain: "A ordem decide. Primeiro separo quem tem menos de 100. Quem sobrou e tem menos de 500 vira Funcionário, inclusive 100 e 499. Só a partir de 500 chega no `else` e vira Diretor.",
        chips: ["if", "elif", "else:", "pontos < 100:", "pontos < 500:", "return", '"Visitante"', '"Funcionário"', '"Diretor"'],
        display: {
          kind: "locks",
          events: [
            { label: "Crachá de 10 pontos", expr: "nivel(10)", expect: "'Visitante'" },
            { label: "Crachá de 100 pontos", expr: "nivel(100)", expect: "'Funcionário'" },
            { label: "Crachá de 499 pontos", expr: "nivel(499)", expect: "'Funcionário'" },
            { label: "Crachá de 500 pontos", expr: "nivel(500)", expect: "'Diretor'" },
          ],
        },
        target: "Leitor de crachás",
        success: { who: "dani", text: "Leitor reprogramado. Com 500 pontos, o seu crachá abre porta de diretor." },
        xp: 20,
      },
      {
        id: "2-3",
        title: "A porta do data center",
        brief: [
          { who: "dani", text: "A porta do data center tem duas regras. Abre se a pessoa tem crachá e o alarme está desligado. Ou abre direto com o código mestre." },
          { who: "dani", text: "`and` quer dizer \"e\": as duas coisas precisam ser verdade. `or` quer dizer \"ou\": basta uma. `not` inverte, e o verdadeiro vira falso." },
          { who: "dani", text: "Em Python, verdadeiro é `True` e falso é `False`. Os parênteses agrupam, como na matemática." },
          { who: "dani", text: "A regra fica assim: `(tem_cracha and not alarme) or codigo_mestre`. O leitor vai testar quatro situações." },
        ],
        task: "Crie `porta_abre(tem_cracha, alarme, codigo_mestre)`: True se tem crachá e o alarme está desligado, ou se tem o código mestre.",
        theory: "Combine condições com `and`, `or` e `not`.",
        example: "pode_sair = tem_chave and not chovendo",
        starter: "def porta_abre(tem_cracha, alarme, codigo_mestre):\n    pass\n",
        hints: ["return (tem_cracha and not alarme) or codigo_mestre"],
        check: 'assert porta_abre(True, False, False) is True\nassert porta_abre(True, True, False) is False, "com alarme ligado não abre"\nassert porta_abre(False, True, True) is True, "o código mestre sempre abre"\nassert porta_abre(False, False, False) is False, "sem crachá não abre"',
        solution: "def porta_abre(tem_cracha, alarme, codigo_mestre):\n    return (tem_cracha and not alarme) or codigo_mestre\n",
        explain: "São duas formas de abrir. A primeira exige crachá `and` alarme desligado (`not alarme`). A segunda é o código mestre, ligado pelo `or`. Sem nenhuma das duas, a porta continua fechada.",
        chips: ["return", "and", "or", "not", "tem_cracha", "alarme", "codigo_mestre", "()"],
        display: {
          kind: "locks",
          events: [
            { label: "Crachá, alarme desligado", expr: "porta_abre(True, False, False)", expect: "True" },
            { label: "Crachá, alarme ligado", expr: "porta_abre(True, True, False)", expect: "False" },
            { label: "Sem crachá, código mestre", expr: "porta_abre(False, True, True)", expect: "True" },
            { label: "Sem nada", expr: "porta_abre(False, False, False)", expect: "False" },
          ],
        },
        target: "Porta do data center",
        success: { who: "dani", text: "A porta obedece a sua lógica agora. Entramos no data center sem disparar nada." },
        xp: 20,
      },
      {
        id: "2-4",
        title: "O rádio da equipe",
        brief: [
          { who: "rui", text: "Léo, grampearam o rádio da equipe. A Bia montou um novo, mas ele precisa responder a quem chama." },
          { who: "dani", text: "Um segredo do Python: coisas vazias contam como falso. O texto vazio `\"\"`, o número `0` e a lista vazia `[]` são falsos." },
          { who: "dani", text: "Então `if not nome:` quer dizer: se não veio nome nenhum. Aí o rádio responde \"Quem fala?\". Se veio, responde \"Na escuta, <nome>\"." },
        ],
        task: 'Crie `chamada(nome)` que retorna "Quem fala?" se o nome for vazio, senão "Na escuta, <nome>".',
        theory: 'Valores vazios (`0`, `""`, `[]`, `None`) contam como falsos.',
        example: 'itens = []\nif not itens:\n    print("Nada aqui")',
        starter: "def chamada(nome):\n    pass\n",
        hints: ["if not nome:", 'return f"Na escuta, {nome}"'],
        check: 'assert chamada("") == "Quem fala?"\nassert chamada("Rui") == "Na escuta, Rui"',
        solution: 'def chamada(nome):\n    if not nome:\n        return "Quem fala?"\n    return f"Na escuta, {nome}"\n',
        explain: "Texto vazio conta como falso, então `not nome` é verdade quando ninguém se identificou. Nesse caso respondo \"Quem fala?\". Com um nome, a f-string monta a resposta.",
        chips: ["if not nome:", "return", '"Quem fala?"', 'f"Na escuta, {nome}"'],
        display: {
          kind: "locks",
          events: [
            { label: "Chamada sem nome", expr: 'chamada("")', expect: "'Quem fala?'" },
            { label: "O Rui chama", expr: 'chamada("Rui")', expect: "'Na escuta, Rui'" },
          ],
        },
        target: "Antena do rádio",
        success: { who: "rui", text: "Na escuta, Léo! Rádio limpo, sem grampo. Agora a gente se fala sem a Vértice ouvir." },
        xp: 20,
      },
      {
        id: "2-5",
        title: "O Sargento Brito",
        boss: "brito",
        brief: [
          { who: "brito", text: "Parado aí! Sou o Sargento Brito, da segurança da Vértice. Ninguém passa pela minha central de rondas." },
          { who: "dani", text: "A central decide o que vigiar a cada minuto. Minuto múltiplo de 3 manda um Guarda. Múltiplo de 5 liga a Câmera. Múltiplo dos dois manda Guarda+Câmera. Senão, só mostra o número." },
          { who: "dani", text: "Múltiplo quer dizer que a divisão não deixa resto. Lembra do `%`? `9 % 3 == 0` é verdade. O `==`, com dois sinais, serve para comparar." },
          { who: "dani", text: "Cuidado com a ordem: 15 é múltiplo de 3 também. Pergunte primeiro o caso dos dois, com `% 15`." },
        ],
        task: 'Crie `ronda(minuto)`: "Guarda+Câmera" se múltiplo de 3 e 5, "Guarda" se de 3, "Câmera" se de 5, senão o número como texto.',
        theory: "`n % 3 == 0` testa se n é múltiplo de 3. A ordem dos `if` importa.",
        example: 'if n % 2 == 0:\n    return "par"',
        starter: "def ronda(minuto):\n    pass\n",
        hints: ["Teste minuto % 15 == 0 primeiro", "No fim, return str(minuto)"],
        check: 'assert ronda(15) == "Guarda+Câmera"\nassert ronda(9) == "Guarda"\nassert ronda(10) == "Câmera"\nassert ronda(7) == "7", "números viram texto"',
        solution: 'def ronda(minuto):\n    if minuto % 15 == 0:\n        return "Guarda+Câmera"\n    if minuto % 3 == 0:\n        return "Guarda"\n    if minuto % 5 == 0:\n        return "Câmera"\n    return str(minuto)\n',
        explain: "Quem é múltiplo de 3 e de 5 é múltiplo de 15, por isso esse teste vem primeiro. Se o do 3 viesse antes, o 15 viraria só \"Guarda\". No fim, `str` transforma o número em texto.",
        chips: ["if", "minuto % 15 == 0:", "minuto % 3 == 0:", "minuto % 5 == 0:", "return", '"Guarda+Câmera"', '"Guarda"', '"Câmera"', "str(minuto)"],
        display: {
          kind: "locks",
          events: [
            { label: "Minuto 15", expr: "ronda(15)", expect: "'Guarda+Câmera'" },
            { label: "Minuto 9", expr: "ronda(9)", expect: "'Guarda'" },
            { label: "Minuto 10", expr: "ronda(10)", expect: "'Câmera'" },
            { label: "Minuto 7", expr: "ronda(7)", expect: "'7'" },
          ],
        },
        target: "Central de rondas",
        success: { who: "dani", text: "Central tomada! Agora a gente sabe onde cada guarda vai estar. O Brito vai acordar com dor de cabeça." },
        xp: 50,
      },
    ],
  },
  {
    id: "w3",
    name: "Capítulo 3: Porto",
    subtitle: "Repetições com for, while e listas",
    emoji: "🚢",
    color: "from-teal-500 to-slate-800",
    sky: ["#14b8a6", "#0f172a"],
    skyline: "#0b1b22",
    levels: [
      {
        id: "3-1",
        title: "Cortina de fumaça",
        brief: [
          { who: "rui", text: "O servidor falso da Vértice chega de navio hoje. Para entrar no porto, a Bia armou bombas de fumaça com contagem regressiva." },
          { who: "dani", text: "Repetir coisas é o trabalho favorito do computador. O comando `for` repete um bloco para cada item de uma sequência." },
          { who: "dani", text: "`range(10, 0, -1)` cria 10, 9, 8... até 1. Ele recebe onde começa, onde para (esse número não entra) e o passo. O -1 conta para trás." },
          { who: "dani", text: "`for i in range(10, 0, -1):` coloca cada número em `i`, um por vez. Mostre cada um e, depois do laço, mostre \"Agora!\"." },
        ],
        task: 'Mostre os números de 10 até 1, um por linha, e depois "Agora!".',
        theory: "`for i in range(início, fim, passo):` repete para cada número. O fim não entra.",
        example: "for i in range(1, 4):\n    print(i)  # 1 2 3",
        starter: "",
        hints: ["for i in range(10, 0, -1):", 'print("Agora!") fora do laço, sem os 4 espaços'],
        check: 'linhas = __out.strip().split("\\n")\nassert linhas == [str(i) for i in range(10, 0, -1)] + ["Agora!"], "Confira a ordem dos números e o Agora! no final"',
        solution: 'for i in range(10, 0, -1):\n    print(i)\nprint("Agora!")\n',
        explain: "`range(10, 0, -1)` produz 10, 9, ..., 1. Cada volta do `for` mostra um número. O `Agora!` fica fora do laço, senão apareceria dez vezes.",
        chips: ["for i in range(10, 0, -1):", "print(i)", 'print("Agora!")'],
        display: { kind: "screen" },
        target: "Detonador de fumaça",
        success: { who: "bia", text: "Fumaça para todo lado! As câmeras do porto não enxergam nada. Vai, vai, vai!" },
        xp: 20,
      },
      {
        id: "3-2",
        title: "A mochila",
        brief: [
          { who: "bia", text: "Antes de entrar no navio, confira o equipamento. Você precisa de lanterna, alicate e o pendrive da Dani." },
          { who: "dani", text: "Uma lista guarda várias coisas em ordem, entre colchetes e separadas por vírgula: `[\"lanterna\", \"alicate\"]`." },
          { who: "dani", text: "`mochila.append(\"pendrive\")` coloca mais um item no fim. E `len(mochila)` conta quantos itens há." },
        ],
        task: 'Crie `mochila` com "lanterna" e "alicate", adicione "pendrive" no fim e guarde o total de itens em `total`.',
        theory: "Listas guardam vários itens. Use `.append()` para adicionar e `len()` para contar.",
        example: 'compras = ["pão"]\ncompras.append("leite")\nprint(len(compras))  # 2',
        starter: "",
        hints: ['mochila = ["lanterna", "alicate"]', "total = len(mochila)"],
        check: 'assert mochila == ["lanterna", "alicate", "pendrive"], f"mochila = {mochila}"\nassert total == 3',
        solution: 'mochila = ["lanterna", "alicate"]\nmochila.append("pendrive")\ntotal = len(mochila)\n',
        explain: "A lista começa com dois itens. `append` põe o pendrive no fim sem apagar nada. `len` conta depois da inclusão, por isso `total` vale 3.",
        chips: ["mochila", "=", '["lanterna", "alicate"]', '.append("pendrive")', "total", "len(mochila)"],
        display: {
          kind: "locks",
          events: [
            { label: "Itens na mochila", expr: "mochila", expect: '["lanterna", "alicate", "pendrive"]' },
            { label: "Total de itens", expr: "total", expect: "3" },
          ],
        },
        target: "Armário de equipamentos",
        success: { who: "bia", text: "Lanterna, alicate e pendrive. Mochila fechada, pode ir." },
        xp: 20,
      },
      {
        id: "3-3",
        title: "Os contêineres",
        brief: [
          { who: "dani", text: "Os contêineres da Vértice têm números pares, e cada número é o peso em toneladas. Quero saber quanto peso a Vértice escondeu no porto." },
          { who: "dani", text: "Comece com um cofrinho vazio: `total = 0`. Percorra a lista com `for n in nums:`." },
          { who: "dani", text: "Se `n % 2 == 0`, o número é par e você soma no cofrinho com `total += n`. No fim, fora do laço, `return total`." },
        ],
        task: "Crie `soma_pares(nums)` que retorna a soma apenas dos números pares da lista.",
        theory: "Percorra a lista com `for` e acumule o resultado numa variável.",
        example: "total = 0\nfor x in [1, 2, 3]:\n    total += x",
        starter: "def soma_pares(nums):\n    pass\n",
        hints: ["Comece com total = 0", "if n % 2 == 0: total += n"],
        check: 'assert soma_pares([1, 2, 3, 4]) == 6\nassert soma_pares([]) == 0\nassert soma_pares([7, 9]) == 0',
        solution: "def soma_pares(nums):\n    total = 0\n    for n in nums:\n        if n % 2 == 0:\n            total += n\n    return total\n",
        explain: "O acumulador começa em 0. Para cada número, `% 2 == 0` diz se ele é par, e só os pares entram na soma. Uma lista vazia não entra no laço e devolve 0.",
        chips: ["total = 0", "for n in nums:", "if n % 2 == 0:", "total += n", "return total"],
        display: {
          kind: "locks",
          events: [
            { label: "Fila 1, 2, 3, 4", expr: "soma_pares([1, 2, 3, 4])", expect: "6" },
            { label: "Fila vazia", expr: "soma_pares([])", expect: "0" },
            { label: "Fila 7, 9", expr: "soma_pares([7, 9])", expect: "0" },
          ],
        },
        target: "Guindaste do porto",
        success: { who: "dani", text: "Achei os contêineres da Vértice. Um deles tem o servidor falso." },
        xp: 25,
      },
      {
        id: "3-4",
        title: "A propina",
        brief: [
          { who: "rui", text: "O Caveira cobra propina dos estivadores, e o valor dobra a cada dia de atraso. Um absurdo." },
          { who: "dani", text: "Quando você não sabe quantas vezes vai repetir, use `while`, que quer dizer \"enquanto\". Ele repete enquanto a condição for verdade." },
          { who: "dani", text: "Comece com valor 1 e dias 0. Enquanto o valor não passar do limite, dobre o valor e some 1 dia." },
          { who: "dani", text: "Cuidado: se a condição nunca ficar falsa, o laço gira para sempre. O terminal corta depois de alguns segundos." },
        ],
        task: "Crie `dias_ate(limite)`: começa em 1, dobra a cada dia até passar do limite e retorna quantos dias passaram.",
        theory: "`while condição:` repete enquanto a condição for verdadeira.",
        example: "n = 1\nwhile n < 100:\n    n *= 2",
        starter: "def dias_ate(limite):\n    pass\n",
        hints: ["valor, dias = 1, 0", "while valor <= limite: valor *= 2 e dias += 1"],
        check: 'assert dias_ate(1) == 1\nassert dias_ate(100) == 7\nassert dias_ate(0) == 0',
        solution: "def dias_ate(limite):\n    valor, dias = 1, 0\n    while valor <= limite:\n        valor *= 2\n        dias += 1\n    return dias\n",
        explain: "Parto de 1 e conto cada dobra. Para o limite 100: 1, 2, 4, 8, 16, 32, 64, e a sétima dobra chega a 128, que já passou. Com limite 0, o 1 já é maior e o laço nem começa.",
        chips: ["valor, dias = 1, 0", "while valor <= limite:", "valor *= 2", "dias += 1", "return dias"],
        display: {
          kind: "locks",
          events: [
            { label: "Limite 1", expr: "dias_ate(1)", expect: "1" },
            { label: "Limite 100", expr: "dias_ate(100)", expect: "7" },
            { label: "Limite 0", expr: "dias_ate(0)", expect: "0" },
          ],
        },
        target: "Planilha do Caveira",
        success: { who: "rui", text: "Com essa planilha a gente prova a extorsão do Caveira. Guarda bem esse arquivo." },
        xp: 25,
      },
      {
        id: "3-5",
        title: "O Tanque",
        boss: "tanque",
        brief: [
          { who: "tanque", text: "Me chamam de Tanque. Ninguém sai do porto com aquele servidor sem passar por mim." },
          { who: "dani", text: "Derrube o Tanque e abra o contêiner. A trava pede o maior número de cada lista, mas a Vértice bloqueou o comando `max`." },
          { who: "dani", text: "Faça como com cartas na mão: segure a primeira como a maior até agora. Olhe as outras e, se alguma for maior, troque." },
          { who: "dani", text: "Se a lista estiver vazia, não há carta nenhuma: devolva `None`, que em Python quer dizer \"nada\"." },
        ],
        task: "Crie `maior(nums)` que retorna o maior número sem usar `max()`. Para uma lista vazia, retorne `None`.",
        theory: "Guarde o melhor valor visto até agora enquanto percorre a lista.",
        example: "melhor = nums[0]",
        starter: "def maior(nums):\n    pass\n",
        hints: ["if not nums: return None", "Compare cada n com melhor"],
        check:
          'import builtins\n_m = builtins.max\nbuiltins.max = lambda *a, **k: (_ for _ in ()).throw(AssertionError("A Vértice bloqueou o max()!"))\ntry:\n    assert maior([3, 9, 2]) == 9\n    assert maior([-5, -1, -9]) == -1, "cuidado com negativos"\n    assert maior([]) is None\nfinally:\n    builtins.max = _m',
        solution: "def maior(nums):\n    if not nums:\n        return None\n    melhor = nums[0]\n    for n in nums:\n        if n > melhor:\n            melhor = n\n    return melhor\n",
        explain: "Primeiro trato a lista vazia. Depois o primeiro número vira o candidato, e cada número seguinte só troca o candidato se for maior. Começar em 0 daria errado com números negativos.",
        chips: ["if not nums:", "return None", "melhor = nums[0]", "for n in nums:", "if n > melhor:", "melhor = n", "return melhor"],
        display: {
          kind: "locks",
          events: [
            { label: "Trava 3, 9, 2", expr: "maior([3, 9, 2])", expect: "9" },
            { label: "Trava -5, -1, -9", expr: "maior([-5, -1, -9])", expect: "-1" },
            { label: "Trava vazia", expr: "maior([])", expect: "None" },
          ],
        },
        target: "Contêiner do servidor",
        success: { who: "dani", text: "Servidor falso nas mãos! Com ele, eu descubro como entrar na Torre Vértice." },
        xp: 60,
      },
    ],
  },
];
