import type { World } from "@/content/types";

export const chaptersB: World[] = [
  {
    id: "w4",
    name: "Capítulo 4: Desmanche",
    subtitle: "Funções, dicionários, tuplas, conjuntos e recursão",
    emoji: "🔧",
    color: "from-amber-500 to-stone-800",
    sky: ["#f59e0b", "#292524"],
    skyline: "#1c1917",
    levels: [
      {
        id: "4-1",
        title: "O turbo",
        brief: [
          { who: "bia", text: "Estou preparando o carro de fuga no desmanche. Ele tem um botão de turbo que dobra a velocidade, mas o painel precisa calcular isso." },
          { who: "dani", text: "Funções podem ter valores padrão. Em `def velocidade(base, turbo=False):`, se ninguém falar do turbo, ele vale `False`, ou seja, desligado." },
          { who: "dani", text: "Se o turbo for `True`, devolva o dobro da base. Senão, devolva a própria base." },
        ],
        task: "Crie `velocidade(base, turbo=False)` que retorna a base, ou a base vezes 2 se o turbo estiver ligado.",
        theory: "Parâmetros podem ter valor padrão: `def f(x, y=2):`.",
        example: "def preco(valor, desconto=0):\n    return valor - desconto",
        starter: "",
        hints: ["def velocidade(base, turbo=False):", "if turbo: return base * 2"],
        check: 'assert velocidade(100) == 100\nassert velocidade(100, True) == 200\nassert velocidade(60, turbo=True) == 120',
        solution: "def velocidade(base, turbo=False):\n    if turbo:\n        return base * 2\n    return base\n",
        explain: "`turbo=False` deixa o segundo valor opcional, então `velocidade(100)` roda sem turbo. Quando alguém passa `True`, a velocidade dobra.",
        chips: ["def velocidade(base, turbo=False):", "if turbo:", "return base * 2", "return base"],
        display: {
          kind: "locks",
          events: [
            { label: "100 km/h sem turbo", expr: "velocidade(100)", expect: "100" },
            { label: "100 km/h com turbo", expr: "velocidade(100, True)", expect: "200" },
            { label: "60 km/h com turbo", expr: "velocidade(60, turbo=True)", expect: "120" },
          ],
        },
        target: "Painel do carro",
        success: { who: "bia", text: "Turbo calibrado. Esse carro vai deixar a Vértice comendo poeira." },
        xp: 25,
      },
      {
        id: "4-2",
        title: "A mensagem cifrada",
        brief: [
          { who: "dani", text: "O servidor do porto tinha uma mensagem cifrada do Hale. Para quebrar a cifra, preciso saber quantas vezes cada letra aparece." },
          { who: "dani", text: "Para isso existe o dicionário. Ele funciona como uma agenda: cada nome aponta para uma informação. `{\"a\": 2}` diz que a letra a aparece 2 vezes." },
          { who: "dani", text: "`cont.get(c, 0)` pergunta quantas vezes a letra já apareceu e responde 0 se for a primeira vez. Some 1 e guarde de novo." },
          { who: "dani", text: "Espaço não é letra: pule com `continue`, que salta para a próxima volta do laço." },
        ],
        task: "Crie `contar_letras(texto)` que retorna um dicionário com quantas vezes cada letra aparece, ignorando espaços.",
        theory: "Dicionários ligam chaves a valores: `{\"a\": 1}`. `.get(chave, padrão)` busca sem dar erro.",
        example: 'placar = {"Hank": 3}\nplacar["Brooke"] = placar.get("Brooke", 0) + 1',
        starter: "def contar_letras(texto):\n    pass\n",
        hints: ["cont = {} e depois for c in texto:", "cont[c] = cont.get(c, 0) + 1"],
        check: 'assert contar_letras("ana") == {"a": 2, "n": 1}\nassert contar_letras("a a") == {"a": 2}, "ignore os espaços"\nassert contar_letras("") == {}',
        solution: 'def contar_letras(texto):\n    cont = {}\n    for c in texto:\n        if c == " ":\n            continue\n        cont[c] = cont.get(c, 0) + 1\n    return cont\n',
        explain: "O dicionário começa vazio e cada letra vira uma chave. `.get(c, 0)` devolve a contagem atual, ou 0 na primeira vez, e eu guardo esse valor mais um. O espaço é pulado com `continue`.",
        chips: ["cont = {}", "for c in texto:", 'if c == " ":', "continue", "cont[c] = cont.get(c, 0) + 1", "return cont"],
        display: {
          kind: "locks",
          events: [
            { label: 'Trecho "ana"', expr: 'contar_letras("ana")', expect: '{"a": 2, "n": 1}' },
            { label: 'Trecho "a a"', expr: 'contar_letras("a a")', expect: '{"a": 2}' },
            { label: "Trecho vazio", expr: 'contar_letras("")', expect: "{}" },
          ],
        },
        target: "Decodificador",
        success: { who: "dani", text: "Cifra quebrada. A mensagem diz: \"servidor no 40º andar, cofre do Kane no desmanche\"." },
        xp: 30,
      },
      {
        id: "4-3",
        title: "As rotas de fuga",
        brief: [
          { who: "rui", text: "Tenho uma lista com os tempos das rotas de fuga, em minutos. Quero a mais rápida e a mais lenta de uma vez." },
          { who: "dani", text: "Uma função pode devolver duas coisas juntas numa tupla: `return a, b`. Tupla é uma listinha que não pode ser alterada." },
          { who: "dani", text: "`min` acha o menor e `max` acha o maior. Junte os dois no `return`." },
        ],
        task: "Crie `min_max(tempos)` que retorna uma tupla (menor, maior).",
        theory: "Tuplas guardam valores fixos: `(x, y)`. `return a, b` devolve uma tupla.",
        example: "def ponto():\n    return 3, 4\nx, y = ponto()",
        starter: "def min_max(tempos):\n    pass\n",
        hints: ["return min(tempos), max(tempos)"],
        check: 'assert min_max([4, 1, 9]) == (1, 9)\nassert min_max([5]) == (5, 5)',
        solution: "def min_max(tempos):\n    return min(tempos), max(tempos)\n",
        explain: "`return a, b` empacota os dois valores numa tupla. `min` e `max` percorrem a lista por você. Com um único tempo, o menor e o maior são o mesmo.",
        chips: ["return", "min(tempos)", ",", "max(tempos)"],
        display: {
          kind: "locks",
          events: [
            { label: "Rotas de 4, 1 e 9 min", expr: "min_max([4, 1, 9])", expect: "(1, 9)" },
            { label: "Uma rota de 5 min", expr: "min_max([5])", expect: "(5, 5)" },
          ],
        },
        target: "GPS do carro",
        success: { who: "rui", text: "Rota de 1 minuto pela avenida do porto. Esse é o nosso caminho de fuga." },
        xp: 25,
      },
      {
        id: "4-4",
        title: "O informante",
        brief: [
          { who: "dani", text: "Tem um informante da Vértice no desmanche. Tenho duas listas de telefones que ligaram para o Kane. Quem aparece nas duas?" },
          { who: "dani", text: "Um conjunto, o `set`, é um saco onde nada se repete. `set([1, 1, 2])` vira `{1, 2}`." },
          { who: "dani", text: "O sinal `&` pega o que está nos dois conjuntos ao mesmo tempo. E `sorted` devolve tudo em ordem, numa lista." },
        ],
        task: "Crie `em_comum(l1, l2)` que retorna uma lista ordenada dos itens presentes nas duas listas, sem repetição.",
        theory: "`set` remove repetidos. `a & b` é a interseção de dois conjuntos.",
        example: "a = {1, 2, 3}\nb = {2, 3, 4}\nprint(a & b)  # {2, 3}",
        starter: "def em_comum(l1, l2):\n    pass\n",
        hints: ["set(l1) & set(l2)", "sorted(...) devolve uma lista"],
        check: 'assert em_comum([1, 2, 2, 3], [2, 3, 4]) == [2, 3]\nassert em_comum([1], [2]) == []',
        solution: "def em_comum(l1, l2):\n    return sorted(set(l1) & set(l2))\n",
        explain: "`set` elimina os repetidos. O `&` fica só com o que existe nos dois conjuntos. `sorted` transforma o resultado numa lista em ordem.",
        chips: ["return", "sorted()", "set(l1)", "&", "set(l2)"],
        display: {
          kind: "locks",
          events: [
            { label: "Listas [1,2,2,3] e [2,3,4]", expr: "em_comum([1, 2, 2, 3], [2, 3, 4])", expect: "[2, 3]" },
            { label: "Listas [1] e [2]", expr: "em_comum([1], [2])", expect: "[]" },
          ],
        },
        target: "Registro de chamadas",
        success: { who: "dani", text: "Achamos o informante: é o Mack, o dono do desmanche. Ele guarda o cofre do Kane." },
        xp: 30,
      },
      {
        id: "4-5",
        title: "O Mack",
        boss: "marreta",
        brief: [
          { who: "marreta", text: "Vocês acharam que eu não ia perceber? O cofre do Kane fica aqui, e daqui ele não sai." },
          { who: "dani", text: "A senha do cofre segue a sequência de Fibonacci: 0, 1, 1, 2, 3, 5, 8... Cada número é a soma dos dois anteriores." },
          { who: "dani", text: "Recursão é quando uma função chama a si mesma, como bonecas russas: cada uma tem uma menor dentro, até a menorzinha." },
          { who: "dani", text: "A menorzinha é o caso base: se n for 0 ou 1, devolva o próprio n. Senão, devolva `fib(n - 1) + fib(n - 2)`." },
        ],
        task: "Crie `fib(n)` recursiva que retorna o n-ésimo número de Fibonacci (fib(0) = 0, fib(1) = 1).",
        theory: "Recursão: a função chama a si mesma, com um caso base para parar.",
        example: "def fatorial(n):\n    return 1 if n <= 1 else n * fatorial(n - 1)",
        starter: "def fib(n):\n    pass\n",
        hints: ["Caso base: if n < 2: return n", "return fib(n - 1) + fib(n - 2)"],
        check: 'assert [fib(i) for i in range(8)] == [0, 1, 1, 2, 3, 5, 8, 13]\nassert fib(15) == 610',
        solution: "def fib(n):\n    if n < 2:\n        return n\n    return fib(n - 1) + fib(n - 2)\n",
        explain: "O caso base impede a recursão infinita: fib(0) é 0 e fib(1) é 1. Qualquer outro número é a soma dos dois anteriores, e cada chamada resolve um problema menor até chegar na base.",
        chips: ["if n < 2:", "return n", "return fib(n - 1) + fib(n - 2)"],
        display: {
          kind: "locks",
          events: [
            { label: "Dígito fib(7)", expr: "fib(7)", expect: "13" },
            { label: "Dígito fib(10)", expr: "fib(10)", expect: "55" },
            { label: "Dígito fib(15)", expr: "fib(15)", expect: "610" },
          ],
        },
        target: "Cofre do Kane",
        success: { who: "caveira", text: "Você abriu o MEU cofre? Com os meus recibos para o Hale? Isso não vai ficar assim, motoboy." },
        xp: 70,
      },
    ],
  },
  {
    id: "w5",
    name: "Capítulo 5: Torre Vértice",
    subtitle: "Classes, herança, métodos especiais e exceções",
    emoji: "🏢",
    color: "from-violet-500 to-slate-900",
    sky: ["#8b5cf6", "#0f0a1e"],
    skyline: "#150f26",
    levels: [
      {
        id: "5-1",
        title: "O disfarce",
        brief: [
          { who: "dani", text: "Estamos no saguão da Torre Vértice. O sistema de segurança acompanha cada agente pela energia da bateria do colete." },
          { who: "dani", text: "Uma classe é um molde. Com o molde de agente, você cria quantos agentes quiser, e cada um é um objeto." },
          { who: "dani", text: "`__init__` é o que acontece quando um agente é criado: guardamos nome e energia dentro dele usando `self`, que quer dizer \"o próprio agente\"." },
          { who: "dani", text: "Crie também o método `levar_dano`, uma ação do agente. A energia diminui, mas nunca fica abaixo de zero: `max(0, ...)` garante isso." },
        ],
        task: "Crie a classe `Agente` com `nome` e `energia=100`, e o método `levar_dano(dano)` que diminui a energia sem deixá-la abaixo de 0.",
        theory: "Classes são moldes. `__init__` monta o objeto e `self` é o próprio objeto.",
        example: 'class Carro:\n    def __init__(self, modelo):\n        self.modelo = modelo\n    def buzinar(self):\n        return "bi-bi"',
        starter: "class Agente:\n    pass\n",
        hints: ["def __init__(self, nome, energia=100):", "self.energia = max(0, self.energia - dano)"],
        check: 'a = Agente("Cole")\nassert a.nome == "Cole" and a.energia == 100\na.levar_dano(30)\nassert a.energia == 70\na.levar_dano(500)\nassert a.energia == 0, "a energia não pode ficar negativa"',
        solution: "class Agente:\n    def __init__(self, nome, energia=100):\n        self.nome = nome\n        self.energia = energia\n\n    def levar_dano(self, dano):\n        self.energia = max(0, self.energia - dano)\n",
        explain: "`__init__` guarda nome e energia no próprio objeto, o `self`. `levar_dano` desconta o dano e usa `max(0, ...)` para a energia nunca ficar negativa.",
        chips: ["def __init__(self, nome, energia=100):", "self.nome = nome", "self.energia = energia", "def levar_dano(self, dano):", "self.energia = max(0, self.energia - dano)"],
        display: {
          kind: "locks",
          setup: 'a = Agente("Cole")',
          events: [
            { label: "Energia inicial do Cole", expr: "a.energia", expect: "100" },
            { label: "Leva um choque de 30", do: "a.levar_dano(30)", expr: "a.energia", expect: "70" },
            { label: "Leva um golpe de 500", do: "a.levar_dano(500)", expr: "a.energia", expect: "0" },
          ],
        },
        target: "Catraca do saguão",
        success: { who: "dani", text: "O sistema aceitou o seu perfil de agente. Você está oficialmente dentro da Torre." },
        xp: 35,
      },
      {
        id: "5-2",
        title: "O crachá de diretor",
        brief: [
          { who: "dani", text: "O elevador para o 40º andar só aceita crachá de diretor. Um crachá de diretor tem o dobro do nível de um crachá comum." },
          { who: "dani", text: "Isso é herança: um filho herda tudo do pai. `class CrachaDiretor(Cracha):` quer dizer que o crachá de diretor é um crachá e já sabe tudo que ele sabe." },
          { who: "dani", text: "Dentro do filho você pode reescrever `nivel`. E `super().nivel()` chama a versão do pai. É só multiplicar por 2." },
        ],
        task: "Crie `Cracha` com o método `nivel()` retornando 10, e `CrachaDiretor(Cracha)` cujo `nivel()` retorna o dobro do nível da classe mãe.",
        theory: "Herança: `class Filha(Mae):`. `super()` chama a classe mãe.",
        example: 'class Animal:\n    def som(self):\n        return "..."\nclass Cao(Animal):\n    def som(self):\n        return "au"',
        starter: "",
        hints: ["class Cracha: com def nivel(self): return 10", "return super().nivel() * 2"],
        check: 'assert Cracha().nivel() == 10\nassert CrachaDiretor().nivel() == 20\nassert isinstance(CrachaDiretor(), Cracha)',
        solution: "class Cracha:\n    def nivel(self):\n        return 10\n\nclass CrachaDiretor(Cracha):\n    def nivel(self):\n        return super().nivel() * 2\n",
        explain: "`CrachaDiretor(Cracha)` herda tudo do crachá comum. Reescrever `nivel` troca o método, mas `super().nivel()` ainda pega o 10 da mãe, e multiplicar por 2 dá 20.",
        chips: ["class Cracha:", "def nivel(self):", "return 10", "class CrachaDiretor(Cracha):", "return super().nivel() * 2"],
        display: {
          kind: "locks",
          events: [
            { label: "Crachá comum", expr: "Cracha().nivel()", expect: "10" },
            { label: "Crachá de diretor", expr: "CrachaDiretor().nivel()", expect: "20" },
            { label: "Diretor também é crachá?", expr: "isinstance(CrachaDiretor(), Cracha)", expect: "True" },
          ],
        },
        target: "Elevador",
        success: { who: "dani", text: "Elevador subindo para o 40º andar. Segura firme." },
        xp: 35,
      },
      {
        id: "5-3",
        title: "Os dutos",
        brief: [
          { who: "bia", text: "O 40º andar tem sensores de movimento. O jeito é seguir pelos dutos de ar, somando os deslocamentos no mapa." },
          { who: "dani", text: "Por trás de cada sinal existe um método especial, com dois tracinhos de cada lado. `+` chama `__add__` e `==` chama `__eq__`." },
          { who: "dani", text: "E `__str__` decide o que aparece quando você mostra o objeto na tela. Ensine a `Coordenada` a fazer as três coisas." },
        ],
        task: 'Crie `Coordenada(x, y)` com `+` (soma x com x e y com y), `==` e `__str__` retornando "Coordenada(x, y)".',
        theory: "Métodos especiais como `__add__`, `__eq__` e `__str__` definem como o objeto funciona com `+`, `==` e `print`.",
        example: "def __add__(self, outro):\n    return Ponto(self.x + outro.x)",
        starter: "class Coordenada:\n    def __init__(self, x, y):\n        self.x, self.y = x, y\n",
        hints: ["def __eq__(self, o): return (self.x, self.y) == (o.x, o.y)", 'return f"Coordenada({self.x}, {self.y})"'],
        check: 'c = Coordenada(1, 2) + Coordenada(3, 4)\nassert c == Coordenada(4, 6)\nassert str(c) == "Coordenada(4, 6)"',
        solution: 'class Coordenada:\n    def __init__(self, x, y):\n        self.x, self.y = x, y\n\n    def __add__(self, outro):\n        return Coordenada(self.x + outro.x, self.y + outro.y)\n\n    def __eq__(self, outro):\n        return (self.x, self.y) == (outro.x, outro.y)\n\n    def __str__(self):\n        return f"Coordenada({self.x}, {self.y})"\n',
        explain: "O `+` chama `__add__`, que devolve uma coordenada nova somando as partes. O `==` chama `__eq__`. O `print` e o `str()` usam `__str__` para montar o texto.",
        chips: ["def __add__(self, outro):", "return Coordenada(self.x + outro.x, self.y + outro.y)", "def __eq__(self, outro):", "def __str__(self):", 'return f"Coordenada({self.x}, {self.y})"'],
        display: {
          kind: "locks",
          events: [
            { label: "(1, 2) + (3, 4)", expr: "str(Coordenada(1, 2) + Coordenada(3, 4))", expect: "'Coordenada(4, 6)'" },
            { label: "(4, 6) == (4, 6)?", expr: "Coordenada(4, 6) == Coordenada(4, 6)", expect: "True" },
          ],
        },
        target: "Grade do duto",
        success: { who: "bia", text: "Você saiu bem em cima da sala do servidor. Nenhum sensor apitou." },
        xp: 40,
      },
      {
        id: "5-4",
        title: "O caixa da propina",
        brief: [
          { who: "dani", text: "Ao lado do servidor fica o caixa da propina do Hale. Vamos reprogramar para ele disparar o alarme quando alguém tentar tirar mais do que tem." },
          { who: "dani", text: "Erros em Python se chamam exceções. Com `try:` você tenta algo arriscado. Com `except:` você diz o que fazer se der errado." },
          { who: "dani", text: "Dividir por zero é impossível e gera `ZeroDivisionError`. Capture esse erro e devolva `None`." },
          { who: "dani", text: "Você também pode disparar um erro de propósito com `raise ValueError(...)`, quando alguém tenta transferir mais do que o saldo." },
        ],
        task: "Crie `dividir(a, b)` que retorna a/b, ou None se b for 0. E `transferir(saldo, valor)` que lança ValueError se o valor for maior que o saldo, senão retorna o novo saldo.",
        theory: "`try/except` captura erros. `raise` dispara um erro.",
        example: 'try:\n    x = int("abc")\nexcept ValueError:\n    x = 0',
        starter: "",
        hints: ["except ZeroDivisionError: return None", 'raise ValueError("saldo insuficiente")'],
        check: 'assert dividir(10, 2) == 5\nassert dividir(1, 0) is None\nassert transferir(100, 30) == 70\ntry:\n    transferir(10, 50)\n    raise AssertionError("transferir deveria lançar ValueError")\nexcept ValueError:\n    pass',
        solution: 'def dividir(a, b):\n    try:\n        return a / b\n    except ZeroDivisionError:\n        return None\n\ndef transferir(saldo, valor):\n    if valor > saldo:\n        raise ValueError("saldo insuficiente")\n    return saldo - valor\n',
        explain: "O `try` tenta a divisão e o `except` transforma o erro de divisão por zero em `None`. Em `transferir`, o erro é de propósito: `raise ValueError` avisa quem chamou que o saldo não basta.",
        chips: ["try:", "return a / b", "except ZeroDivisionError:", "return None", "if valor > saldo:", 'raise ValueError("saldo insuficiente")', "return saldo - valor"],
        display: {
          kind: "locks",
          events: [
            { label: "Dividir 10 por 2", expr: "dividir(10, 2)", expect: "5.0" },
            { label: "Dividir 1 por 0", expr: "dividir(1, 0)", expect: "None" },
            { label: "Transferir 30 de 100", expr: "transferir(100, 30)", expect: "70" },
            { label: "Transferir 50 de 10", expr: "transferir(10, 50)", expect: "!ValueError" },
          ],
        },
        target: "Caixa da propina",
        success: { who: "dani", text: "Pronto. Cada saque ilegal agora fica registrado. É mais uma prova contra o Hale." },
        xp: 40,
      },
      {
        id: "5-5",
        title: "O Kane",
        boss: "caveira",
        brief: [
          { who: "caveira", text: "Achou mesmo que ia chegar no servidor, motoboy? Hoje a dívida vai ser cobrada inteira." },
          { who: "dani", text: "Derrube o Kane e pegue o controle do cofre de provas. Ele funciona com uma classe `Cofre`, que guarda documentos por nome e quantidade." },
          { who: "dani", text: "`guardar` soma na quantidade. `retirar` confere antes e, se não houver o suficiente, dispara o erro `SemDocumento`." },
          { who: "dani", text: "E `__len__` ensina o `len()` a contar todos os documentos, somando os valores do dicionário." },
        ],
        task: "Crie `SemDocumento(Exception)` e `Cofre` com `guardar(doc, qtd=1)`, `retirar(doc, qtd=1)` (lança SemDocumento se não houver o suficiente), `qtd(doc)` e `len()` com o total.",
        theory: "Junte tudo: classe, dicionário interno, exceção própria e `__len__`.",
        example: "class MeuErro(Exception):\n    pass",
        starter: "class SemDocumento(Exception):\n    pass\n\nclass Cofre:\n    def __init__(self):\n        self.docs = {}\n",
        hints: ["self.docs.get(doc, 0)", "def __len__(self): return sum(self.docs.values())"],
        check:
          'c = Cofre()\nc.guardar("recibo", 3)\nc.guardar("foto")\nassert c.qtd("recibo") == 3 and len(c) == 4\nc.retirar("recibo", 2)\nassert c.qtd("recibo") == 1\nassert c.qtd("nada") == 0\ntry:\n    c.retirar("foto", 5)\n    raise AssertionError("deveria lançar SemDocumento")\nexcept SemDocumento:\n    pass',
        solution: "class SemDocumento(Exception):\n    pass\n\nclass Cofre:\n    def __init__(self):\n        self.docs = {}\n\n    def guardar(self, doc, qtd=1):\n        self.docs[doc] = self.docs.get(doc, 0) + qtd\n\n    def retirar(self, doc, qtd=1):\n        if self.qtd(doc) < qtd:\n            raise SemDocumento(doc)\n        self.docs[doc] -= qtd\n\n    def qtd(self, doc):\n        return self.docs.get(doc, 0)\n\n    def __len__(self):\n        return sum(self.docs.values())\n",
        explain: "O dicionário liga cada documento à sua quantidade. `guardar` soma usando 0 para documentos novos. `retirar` confere antes e dispara `SemDocumento`, uma exceção criada por nós. `__len__` soma tudo.",
        chips: ["def guardar(self, doc, qtd=1):", "self.docs[doc] = self.docs.get(doc, 0) + qtd", "def retirar(self, doc, qtd=1):", "raise SemDocumento(doc)", "def qtd(self, doc):", "def __len__(self):", "return sum(self.docs.values())"],
        display: {
          kind: "locks",
          setup: "c = Cofre()",
          events: [
            { label: "Guarda 3 recibos", do: 'c.guardar("recibo", 3)', expr: 'c.qtd("recibo")', expect: "3" },
            { label: "Guarda 1 foto. Total?", do: 'c.guardar("foto")', expr: "len(c)", expect: "4" },
            { label: "Retira 2 recibos", do: 'c.retirar("recibo", 2)', expr: 'c.qtd("recibo")', expect: "1" },
            { label: "Tenta tirar 5 fotos", expr: 'c.retirar("foto", 5)', expect: "!SemDocumento" },
          ],
        },
        target: "Cofre de provas",
        success: { who: "rui", text: "O Kane está algemado com os próprios lacres. Cole, sua dívida acabou. Agora falta o Hale." },
        xp: 90,
      },
    ],
  },
  {
    id: "w6",
    name: "Capítulo 6: O Golpe",
    subtitle: "Compreensões, lambda, geradores, decorators e dataclasses",
    emoji: "💼",
    color: "from-rose-500 to-zinc-900",
    sky: ["#e11d48", "#09090b"],
    skyline: "#18080c",
    levels: [
      {
        id: "6-1",
        title: "A chave de criptografia",
        brief: [
          { who: "dani", text: "O servidor está na nossa frente. A chave de acesso é a lista dos quadrados dos números ímpares da sequência." },
          { who: "dani", text: "Uma compreensão de lista cria uma lista numa linha só, e quase dá para ler em português: `[n ** 2 for n in nums if n % 2]`." },
          { who: "dani", text: "Quer dizer: o quadrado de n, para cada n em nums, se n for ímpar. `**` é potência, e `n % 2` diferente de zero indica ímpar." },
        ],
        task: "Crie `quadrados_impares(nums)` que retorna, com uma compreensão, os quadrados dos números ímpares.",
        theory: "Compreensão de lista: `[expressão for item in lista if condição]`.",
        example: "dobros = [x * 2 for x in [1, 2, 3]]",
        starter: "def quadrados_impares(nums):\n    pass\n",
        hints: ["return [n ** 2 for n in nums if n % 2]"],
        check: 'assert quadrados_impares([1, 2, 3, 4, 5]) == [1, 9, 25]\nassert quadrados_impares([2]) == []',
        solution: "def quadrados_impares(nums):\n    return [n ** 2 for n in nums if n % 2]\n",
        explain: "O `if` no fim filtra os ímpares, e o que vem antes do `for` é o valor novo, `n ** 2`. Os pares ficam de fora da lista.",
        chips: ["return", "[n ** 2 for n in nums if n % 2]"],
        display: {
          kind: "locks",
          events: [
            { label: "Sequência 1 a 5", expr: "quadrados_impares([1, 2, 3, 4, 5])", expect: "[1, 9, 25]" },
            { label: "Sequência só com 2", expr: "quadrados_impares([2])", expect: "[]" },
          ],
        },
        target: "Tela do servidor",
        success: { who: "dani", text: "Chave aceita. Estamos no sistema da Vértice." },
        xp: 40,
      },
      {
        id: "6-2",
        title: "A lista de alvos",
        brief: [
          { who: "dani", text: "O Hale tem uma lista de pessoas que ele vigia, cada uma com um nível de risco. Quero saber quem está mais em perigo primeiro." },
          { who: "dani", text: "`lambda` é uma mini função sem nome, escrita na hora: `lambda p: p[1]` recebe uma pessoa e devolve o risco, que está na posição 1." },
          { who: "dani", text: "`sorted(pessoas, key=..., reverse=True)` ordena por esse critério, do maior para o menor. Depois pegue só os nomes com uma compreensão." },
        ],
        task: "Crie `ordenar_por_risco(pessoas)` que recebe tuplas (nome, risco) e retorna só os nomes, do maior risco para o menor.",
        theory: "`lambda x: ...` é uma função curta. `sorted(lista, key=...)` ordena por um critério.",
        example: 'palavras = sorted(["ab", "c"], key=lambda s: len(s))',
        starter: "def ordenar_por_risco(pessoas):\n    pass\n",
        hints: ["ordem = sorted(pessoas, key=lambda p: p[1], reverse=True)", "return [nome for nome, risco in ordem]"],
        check: 'assert ordenar_por_risco([("Ana", 5), ("Beto", 9), ("Caio", 1)]) == ["Beto", "Ana", "Caio"]',
        solution: "def ordenar_por_risco(pessoas):\n    ordem = sorted(pessoas, key=lambda p: p[1], reverse=True)\n    return [nome for nome, risco in ordem]\n",
        explain: "Cada pessoa é uma tupla (nome, risco). `sorted` com `key=lambda p: p[1]` ordena pelo risco, e `reverse=True` coloca o maior primeiro. A compreensão fica só com os nomes.",
        chips: ["ordem = sorted(pessoas, key=lambda p: p[1], reverse=True)", "return [nome for nome, risco in ordem]"],
        display: {
          kind: "locks",
          events: [
            { label: "Ana 5, Beto 9, Caio 1", expr: 'ordenar_por_risco([("Ana", 5), ("Beto", 9), ("Caio", 1)])', expect: '["Beto", "Ana", "Caio"]' },
          ],
        },
        target: "Arquivo de vigilância",
        success: { who: "dani", text: "O primeiro da lista é meu irmão. Vamos tirar ele de lá." },
        xp: 45,
      },
      {
        id: "6-3",
        title: "O bloqueador de sinal",
        brief: [
          { who: "bia", text: "Os drones da Torre vão cercar o prédio. Montei um bloqueador de sinal, mas ele precisa de pulsos que dobram de força, 1, 2, 4, 8, para sempre." },
          { who: "dani", text: "Uma lista infinita não cabe na memória. Um gerador cabe: ele entrega um valor de cada vez, só quando pedem." },
          { who: "dani", text: "Troque `return` por `yield`: a função entrega o valor, pausa e continua dali quando pedirem o próximo." },
        ],
        task: "Crie o gerador infinito `potencias_de_2()`: 1, 2, 4, 8, ...",
        theory: "`yield` cria um gerador, que produz valores sob demanda.",
        example: "def contar():\n    n = 0\n    while True:\n        yield n\n        n += 1",
        starter: "def potencias_de_2():\n    pass\n",
        hints: ["n = 1 e depois while True:", "yield n e em seguida n *= 2"],
        check: 'import itertools, types\ng = potencias_de_2()\nassert isinstance(g, types.GeneratorType), "use yield"\nassert list(itertools.islice(g, 6)) == [1, 2, 4, 8, 16, 32]',
        solution: "def potencias_de_2():\n    n = 1\n    while True:\n        yield n\n        n *= 2\n",
        explain: "`yield` pausa a função e entrega um valor sem montar uma lista infinita. Na próxima leitura, ela continua logo depois do `yield` e dobra o `n`.",
        chips: ["n = 1", "while True:", "yield n", "n *= 2"],
        display: {
          kind: "locks",
          setup: "import itertools, types",
          events: [
            { label: "É um gerador?", expr: "isinstance(potencias_de_2(), types.GeneratorType)", expect: "True" },
            { label: "Primeiros 6 pulsos", expr: "list(itertools.islice(potencias_de_2(), 6))", expect: "[1, 2, 4, 8, 16, 32]" },
          ],
        },
        target: "Bloqueador de sinal",
        success: { who: "bia", text: "Os drones estão caindo como moscas. O céu está livre!" },
        xp: 50,
      },
      {
        id: "6-4",
        title: "O download das provas",
        brief: [
          { who: "dani", text: "Hora de baixar as provas. Mas preciso saber quantas vezes o download rodou, para não deixar rastro. Não quero mexer no código do download em si." },
          { who: "dani", text: "Um decorator é como um embrulho: você embrulha uma função com outra, que faz algo a mais antes de chamar a original." },
          { who: "dani", text: "O `@contar_chamadas` em cima do `def` embrulha a função. O embrulho soma 1 no contador e depois chama a função de verdade." },
        ],
        task: 'Crie o decorator `contar_chamadas`, que guarda em `funcao.chamadas` quantas vezes ela foi chamada. Use-o em `def baixar(): return "ok"`.',
        theory: "Um decorator recebe uma função e devolve outra no lugar. Use `@nome` acima do `def`.",
        example: "def grito(f):\n    def w(*a, **k):\n        return f(*a, **k).upper()\n    return w",
        starter: 'def contar_chamadas(f):\n    pass\n\n@contar_chamadas\ndef baixar():\n    return "ok"\n',
        hints: ["def wrapper(*a, **k): wrapper.chamadas += 1; return f(*a, **k)", "wrapper.chamadas = 0 e depois return wrapper"],
        check: 'assert baixar.chamadas == 0\nassert baixar() == "ok"\nbaixar(); baixar()\nassert baixar.chamadas == 3',
        solution: 'def contar_chamadas(f):\n    def wrapper(*a, **k):\n        wrapper.chamadas += 1\n        return f(*a, **k)\n    wrapper.chamadas = 0\n    return wrapper\n\n@contar_chamadas\ndef baixar():\n    return "ok"\n',
        explain: "O decorator recebe `baixar` e devolve o `wrapper` no lugar. Cada chamada soma 1 em `wrapper.chamadas` e só então chama a função original, repassando os argumentos.",
        chips: ["def wrapper(*a, **k):", "wrapper.chamadas += 1", "return f(*a, **k)", "wrapper.chamadas = 0", "return wrapper"],
        display: {
          kind: "locks",
          events: [
            { label: "Antes de baixar", expr: "baixar.chamadas", expect: "0" },
            { label: "Baixa uma vez", do: "baixar()", expr: "baixar.chamadas", expect: "1" },
            { label: "Baixa mais duas", do: "baixar(); baixar()", expr: "baixar.chamadas", expect: "3" },
          ],
        },
        target: "Download das provas",
        success: { who: "dani", text: "Provas baixadas. Três arquivos, nenhum rastro. Agora só falta publicar." },
        xp: 55,
      },
      {
        id: "6-5",
        title: "Victor Hale",
        boss: "vidal",
        brief: [
          { who: "vidal", text: "Impressionante. Um motoboy e uma ex-funcionária chegaram até a minha sala. Pena que as provas não saem deste prédio." },
          { who: "dani", text: "Última lição, Cole. `@dataclass` cria uma classe de dados sem precisar escrever o `__init__`. Você só lista os campos e seus tipos." },
          { who: "dani", text: "`nome: str` quer dizer que nome é texto. `valor: int` é um número. `publicada: bool = False` começa como não publicada." },
          { who: "dani", text: "Depois, some o valor das provas que ainda não foram publicadas, e indique que a função devolve um número com `-> int`. Derrube os seguranças do Hale e chegue ao terminal." },
        ],
        task: "Crie a dataclass `Prova(nome: str, valor: int, publicada: bool = False)` e a função `total_pendente(provas: list[Prova]) -> int`, que soma o valor das provas não publicadas.",
        theory: "`@dataclass` gera `__init__`, `__eq__` e `__repr__`. Type hints (`nome: str`) documentam os tipos.",
        example: "from dataclasses import dataclass\n\n@dataclass\nclass Ponto:\n    x: int\n    y: int = 0",
        starter: "from dataclasses import dataclass\n",
        hints: ["@dataclass acima de class Prova:", "sum(p.valor for p in provas if not p.publicada)"],
        check:
          'import dataclasses\nassert dataclasses.is_dataclass(Prova), "use @dataclass"\nps = [Prova("a", 10), Prova("b", 5, True), Prova("c", 7)]\nassert total_pendente(ps) == 17\nassert Prova("x", 1) == Prova("x", 1)\nassert total_pendente.__annotations__.get("return") in (int, "int"), "indique o retorno com -> int"',
        solution: "from dataclasses import dataclass\n\n@dataclass\nclass Prova:\n    nome: str\n    valor: int\n    publicada: bool = False\n\ndef total_pendente(provas: list[Prova]) -> int:\n    return sum(p.valor for p in provas if not p.publicada)\n",
        explain: "`@dataclass` gera o construtor e a comparação a partir dos campos. `publicada` começa como `False`. `total_pendente` soma só o valor das provas ainda não publicadas, e `-> int` indica que o resultado é um número.",
        chips: ["@dataclass", "class Prova:", "nome: str", "valor: int", "publicada: bool = False", "def total_pendente(provas: list[Prova]) -> int:", "return sum(p.valor for p in provas if not p.publicada)"],
        display: {
          kind: "locks",
          setup: 'ps = [Prova("Contratos", 10), Prova("Vídeos", 5, True), Prova("Recibos", 7)]',
          events: [
            { label: "Prova é uma dataclass?", expr: "__import__('dataclasses').is_dataclass(Prova)", expect: "True" },
            { label: "Valor ainda não publicado", expr: "total_pendente(ps)", expect: "17" },
            { label: 'Prova("x", 1) == Prova("x", 1)?', expr: 'Prova("x", 1) == Prova("x", 1)', expect: "True" },
          ],
        },
        target: "Transmissão para a imprensa",
        success: { who: "dani", text: "Está no ar em todos os jornais. O Hale foi preso, e meu irmão vai sair. Cole, você começou sem saber nada e derrubou a Vértice. Obrigada, parceiro." },
        xp: 120,
      },
    ],
  },
];
